### ISSUE TITLE
Error when creating an expense report

### ISSUE THREAD

**Issue by genonioff** [mikaelcarlavan/ndfp#1]
Thank you so much for your module. It looks great! Only, when I try to create mileage expenses, I get this error:

Unknown column 'comment_user' in 'field list' sql=INSERT INTO my_ndfp (`ref`, `cur_iso`, `entity`, `datec`, `dates`, `datee`, `datef`, `fk_user_author`, `fk_user`, `statut`, `fk_soc`, `fk_project`, `fk_cat`, `fk_mode_reglement`, `billed`, `total_tva`, `total_ht`, `total_ttc`, `description`, `comment_user`, `comment_admin`, `model_pdf`, `tms`) VALUES ( '(PROV)' , 'EUR' , '1' , '2022-06-01 15:34:40', '2022-06-01 12:00:00', '2022-06-01 12:00:00', '2022-06-01 15:34:40', 1, 1, 0, 6, 0, 8, 5, 0, 0, 0, 0, 'super description', 'ddddddd', '', 'calamar', '2022-06-01 15:34:40')

**Comment by mikaelcarlavan** [comment]
Some columns are missing in the structure of tables. Executing the following queries should solve the problem:
ALTER TABLE `my_ndfp` ADD `comment_user` TEXT DEFAULT NULL;
ALTER TABLE `my_ndfp` ADD `comment_admin` TEXT DEFAULT NULL;

**Comment by genonioff** [comment]
Thank you so much
